version: "3.9"

services:
  angular-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - necro_api
    restart: always

  necrofinances:
    image: necrofinancesbackend-api
    container_name: necro_api
    expose:
      - "8080"
    restart: unless-stopped